kind: PersistentVolume
apiVersion: v1
metadata:
  name: shinobi-data
spec:
  storageClassName: shinobi-data
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/video/shinobi/data"
