kind: PersistentVolume
apiVersion: v1
metadata:
  name: shinobi-mysql
spec:
  storageClassName: shinobi-mysql
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/video/shinobi/mysql"
