kind: PersistentVolume
apiVersion: v1
metadata:
  name: shinobi-mysql
spec:
  storageClassName: shinobi-mysql
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shinobi/mysql"
