{{- if .Values.configurator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "home-assistant.fullname" . }}-configurator
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.configurator.hassApiPassword }}
  hass-api-password: {{ .Values.configurator.hassApiPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.configurator.configurator_username }}
  username: {{ .Values.configurator.configurator_username | b64enc | quote }}
  {{- end }}
  {{- if .Values.configurator.configurator_password }}
  password: {{ .Values.configurator.configurator_password | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.vscode.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "home-assistant.fullname" . }}-vscode
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.vscode.password }}
  password: {{ .Values.vscode.password | b64enc | quote }}
  {{- end }}
{{- end }}
