kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-data
  labels:
    type: local
spec:
  storageClassName: home-assistant-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/home-assistant/data"
