kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: hass
  labels:
    type: local
spec:
  storageClassName: home-assistant-config
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/home-assistant/config"
