kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant
  labels:
    type: local
spec:
  storageClassName: home-assistant
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/home-assistant"
