kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: hass
spec:
  storageClassName: home-assistant-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
