kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-data
spec:
  storageClassName: home-assistant-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
