kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-mysql
  labels:
    type: local
spec:
  storageClassName: home-assistant-mysql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/home-assistant/mysql"
