apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shinobi.fullname" . }}-cron-configuration
data:
  conf.json: |-
    {
      "ip": "{{ template "shinobi.fullname" . }}",
      "port": {{ .Values.service.port }},
      "db": {
        "host": "{{ template "mysql.fullname" . }}",
        "user": {{ .Values.mysql.mysqlUser | quote }},
        "password": {{ .Values.mysql.mysqlPassword | quote }},
        "database": {{ .Values.mysql.mysqlDatabase | quote }},
        "port": {{ .Values.mysql.service.port }}
      },
      {{- with .Values.shinobi.app.conf.cron }}
      "cron":{
          "key": {{ .key | quote }}
      }
      {{- end }}
    }
