# Default values for home-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: msuossianpe/dasshio
  tag: 728
  pullPolicy: IfNotPresent
  pullSecrets: []

# Used for authenticating with home assistant
token:  

dataPaths:
  doorbell: /mnt/home-assistant/config/dasshio/doorbell
  kitchen: /mnt/home-assistant/config/dasshio/kitchen
  laundryRoom: /mnt/home-assistant/config/dasshio/laundry_room
  livingRoom: /mnt/home-assistant/config/dasshio/living_room
  petersRoom: /mnt/home-assistant/config/dasshio/peters_room
  remotes: /mnt/home-assistant/config/dasshio/remotes

priorityClassName: hass-critical

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

ssl:
  enable: false

hostNetwork: true

## Additional hass container environment variable
## For instance to add a http_proxy
##
extraEnv: {}

## Additional hass container environment variable from k8s secrets
## For instance to add a password
## can use `!env_var` in the home assistant configuration to reference these variables
extraEnvSecrets:
  # Example
  # This will set ${MQTT_PASSWORD} to the 'password' key from the 'mqtt' secret
  # MQTT_PASSWORD:
  #   secret: mqtt
  #   key: password

# Enable pod security context (must be `true` if runAsUser or fsGroup are set)
usePodSecurityContext: true
# Set runAsUser to 1000 to let home-assistant run as non-root user 'hass' which exists in 'runningman84/alpine-homeassistant' docker image.
# When setting runAsUser to a different value than 0 also set fsGroup to the same value:
# runAsUser: <defaults to 0>
# fsGroup: <will be omitted in deployment if runAsUser is 0>

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
   cpu: 20m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  container.apparmor.security.beta.kubernetes.io/dasshio-doorbell: unconfined
  container.apparmor.security.beta.kubernetes.io/dasshio-kitchen: unconfined
  container.apparmor.security.beta.kubernetes.io/dasshio-laundryroom: unconfined
  container.apparmor.security.beta.kubernetes.io/dasshio-livingroom: unconfined
  container.apparmor.security.beta.kubernetes.io/dasshio-petersroom: unconfined
  container.apparmor.security.beta.kubernetes.io/dasshio-remotes: unconfined
