# Default values for home-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: msuossianpe/dasshio
  tag: 727
  pullPolicy: IfNotPresent
  pullSecrets: []

# Used for authenticating with home assistant
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiNjM4MmVlNjI3NTc0OWJjYjMzMTkzZGNjZDE0MDhhMSIsImlhdCI6MTU2NDI2ODA0OCwiZXhwIjoxODc5NjI4MDQ4fQ.IUo7hz2G7mtTLK9UFGHcoVFgPALnujNRb9XUy9oE0qo

dataPath: /mnt/home-assistant/config/dasshio

priorityClassName: hass-critical

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

hostNetwork: true

## Additional hass container environment variable
## For instance to add a http_proxy
##
extraEnv: {}

## Additional hass container environment variable from k8s secrets
## For instance to add a password
## can use `!env_var` in the home assistant configuration to reference these variables
extraEnvSecrets:
  # Example
  # This will set ${MQTT_PASSWORD} to the 'password' key from the 'mqtt' secret
  # MQTT_PASSWORD:
  #   secret: mqtt
  #   key: password

# Enable pod security context (must be `true` if runAsUser or fsGroup are set)
usePodSecurityContext: true
# Set runAsUser to 1000 to let home-assistant run as non-root user 'hass' which exists in 'runningman84/alpine-homeassistant' docker image.
# When setting runAsUser to a different value than 0 also set fsGroup to the same value:
# runAsUser: <defaults to 0>
# fsGroup: <will be omitted in deployment if runAsUser is 0>

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  container.apparmor.security.beta.kubernetes.io/dasshio: unconfined
