apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dasshio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dasshio.name" . }}
    helm.sh/chart: {{ include "dasshio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dasshio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dasshio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: dasshio-doorbell
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-doorbell
        - name: dasshio-kitchen
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-kitchen
        - name: dasshio-laundryroom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-laundryroom
        - name: dasshio-livingroom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-livingroom
        - name: dasshio-petersroom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-petersroom
        - name: dasshio-remotes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASSIO_TOKEN
              value: {{ .Values.token }}
            {{- if .Values.ssl.enable }}
            - name: SSL_ENABLED
              value: True
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: /data
            name: dasshio-remotes
      {{- if .Values.priorityClassName }}      
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
      - name: dasshio-doorbell
        hostPath:
          path: {{.Values.dataPaths.doorbell }}
      - name: dasshio-kitchen
        hostPath:
          path: {{.Values.dataPaths.kitchen }}
      - name: dasshio-laundryroom
        hostPath:
          path: {{.Values.dataPaths.laundryRoom }}
      - name: dasshio-livingroom
        hostPath:
          path: {{.Values.dataPaths.livingRoom }}
      - name: dasshio-petersroom
        hostPath:
          path: {{.Values.dataPaths.petersRoom }}
      - name: dasshio-remotes
        hostPath:
          path: {{.Values.dataPaths.remotes }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
