kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-pv
  labels:
    type: local
spec:
  storageClassName: ha
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kube_data"
