apiVersion: v1
kind: Service
metadata:
  name: hass-external
  labels:
    app.kubernetes.io/instance: hass
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: configurator
    port: 31546
    protocol: TCP
    targetPort: 31546
  selector:
    app: home-assistant
    release: hass
  loadBalancerIP: 192.168.29.100
  type: LoadBalancer
