apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "esphome.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "esphome.name" . }}
    helm.sh/chart: {{ include "esphome.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "esphome.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "esphome.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: esphome
          image: "{{ .Values.components.esphome.image.repository }}:{{ .Values.components.esphome.image.tag }}"
          imagePullPolicy: {{ .Values.components.esphome.image.pullPolicy }}
          ports:
            - name: esphome
              containerPort: {{ .Values.components.esphome.service.port }}
              protocol: TCP
          volumeMounts:
          - mountPath: /config
            name: component-esphome-config
      volumes:
      - name: component-esphome-config
        hostPath:
          path: {{.Values.components.esphome.dataPath }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
