apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "home-assistant.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "home-assistant.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "home-assistant.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      initContainers:
      {{- if .Values.git.enabled }}
      - name: git-sync
        image: "{{ .Values.git.image.repository }}:{{ .Values.git.image.tag }}"
        imagePullPolicy: {{ .Values.git.image.pullPolicy }}
        command: ['sh', '-c', '[ "$(ls {{ .Values.git.syncPath }})" ] || git clone {{ .Values.git.repo }} {{ .Values.git.syncPath }}']
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: {{ .Values.git.keyPath }}
          name: git-secret
        {{- if .Values.usePodSecurityContext }}
        securityContext:
          runAsUser: {{ default 0 .Values.runAsUser }}
        {{- if and (.Values.runAsUser) (.Values.fsGroup) }}
        {{- if not (eq .Values.runAsUser 0.0) }}
          fsGroup: {{ .Values.fsGroup }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            {{- range $name, $opts := .Values.extraEnvSecrets }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $opts.secret }}
                  key: {{ $opts.key }}
            {{- end }}
          volumeMounts:
          - mountPath: /config
            name: config
          {{- if .Values.zwave.enabled }}
          - mountPath: /dev/ttyACM0
            name: ttyacm
          {{- end }}
          {{- if .Values.zigbee.enabled }}
          - mountPath: /dev/ttyACM1
            name: ttyacm1
          {{- end }}
          {{- if .Values.git.enabled }}
          - mountPath: {{ .Values.git.keyPath }}
            name: git-secret
          {{- end }}
          {{- if .Values.usePodSecurityContext }}
          securityContext:
            runAsUser: {{ default 0 .Values.runAsUser }}
          {{- if and (.Values.runAsUser) (.Values.fsGroup) }}
          {{- if not (eq .Values.runAsUser 0.0) }}
            fsGroup: {{ .Values.fsGroup }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- if (.Values.zwave.enabled) or (.Values.zigbee.enabled) }}
          securityContext:
            privileged: true
          {{- end }}
        {{- if .Values.hassioSupervisor.enabled }}
        - name: hassio-supervisor
          image: "{{ .Values.hassioSupervisor.image.repository }}:{{ .Values.hassioSupervisor.image.tag }}"
          imagePullPolicy: {{ .Values.hassioSupervisor.image.pullPolicy }}
#          ports:
#            - name: hassio-super
#              containerPort: {{ .Values.hassioSupervisor.service.port }}
#              protocol: TCP
          env:
            {{- if .Values.hassioSupervisor.supervisorName }}
            - name: SUPERVISOR_NAME
              value: "{{ .Values.hassioSupervisor.supervisorName }}"
            {{- end }}
            {{- if .Values.hassioSupervisor.supervisorShare }}
            - name: SUPERVISOR_SHARE
              value: "{{ .Values.hassioSupervisor.supervisorShare }}"
            {{- end }}
            {{- if .Values.hassioSupervisor.homeassistantRepository }}
            - name: HOMEASSISTANT_REPOSITORY
              value: "{{ .Values.hassioSupervisor.homeassistantRepository }}"
            {{- end }}
            {{- range $key, $value := .Values.hassioSupervisor.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          volumeMounts:
          {{- if .Values.hassioSupervisor.dataDirectory }}
          - mountPath: /data/
            name: hassio-data
          {{- end }}
          {{- if .Values.hassioSupervisor.dockerSock }}
          - mountPath: /var/run/docker.sock
            name: hassio-dsock
          {{- end }}
          {{- if .Values.hassioSupervisor.dbus }}
          - mountPath: /var/run/dbus
            name: hassio-dbus
          {{- end }}
          {{- if .Values.usePodSecurityContext }}
          securityContext:
            runAsUser: {{ default 0 .Values.runAsUser }}
          {{- if and (.Values.runAsUser) (.Values.fsGroup) }}
          {{- if not (eq .Values.runAsUser 0.0) }}
            fsGroup: {{ .Values.fsGroup }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.hassioSupervisor.resources | indent 12 }}
          securityContext:
            privileged: true
        {{- end }}
        {{- if .Values.configurator.enabled }}
        - name: configurator
          image: "{{ .Values.configurator.image.repository }}:{{ .Values.configurator.image.tag }}"
          imagePullPolicy: {{ .Values.configurator.image.pullPolicy }}
          ports:
            - name: configurator
              containerPort: {{ .Values.configurator.service.port }}
              protocol: TCP
          env:
            {{- if .Values.configurator.hassApiPassword }}
            - name: HC_HASS_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "home-assistant.fullname" . }}-configurator
                  key: hass-api-password
            {{- end }}
            {{- if (.Values.configurator.username) and (.Values.configurator.password) }}
            - name: HC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "home-assistant.fullname" . }}-configurator
                  key: username
            - name: HC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "home-assistant.fullname" . }}-configurator
                  key: password
            {{- end }}
            {{- if .Values.configurator.hassApiUrl }}
            - name: HC_HASS_API
              value: "{{ .Values.configurator.hassApiUrl }}"
            {{- else }}
            - name: HC_HASS_API
              value: "http://127.0.0.1:8123/api/"
            {{- end }}
            {{- if .Values.configurator.basepath }}
            - name: HC_BASEPATH
              value: "{{ .Values.configurator.basepath }}"
            {{- end }}
            {{- if .Values.configurator.enforceBasepath }}
            - name: HC_ENFORCE_BASEPATH
              value: "{{ .Values.configurator.enforceBasepath }}"
            {{- end }}
            {{- range $key, $value := .Values.configurator.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          volumeMounts:
          - mountPath: /config
            name: config
          {{- if .Values.git.enabled }}
          - mountPath: {{ .Values.git.keyPath }}
            name: git-secret
          {{- end }}
          {{- if .Values.usePodSecurityContext }}
          securityContext:
            runAsUser: {{ default 0 .Values.runAsUser }}
          {{- if and (.Values.runAsUser) (.Values.fsGroup) }}
          {{- if not (eq .Values.runAsUser 0.0) }}
            fsGroup: {{ .Values.fsGroup }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.configurator.resources | indent 12 }}
        {{- end }}
        {{- if .Values.vscode.enabled }}
        - name: vscode
          image: "{{ .Values.vscode.image.repository }}:{{ .Values.vscode.image.tag }}"
          imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
          workingDir: {{ .Values.vscode.hassConfig }}
          args:
            - --allow-http
            - --port={{ .Values.vscode.service.port }}
            {{- if not (.Values.vscode.password) }}
            - --no-auth
            {{- end }}
            {{- if .Values.vscode.vscodePath }}
            - --extensions-dir={{ .Values.vscode.vscodePath }}
            - --user-data-dir={{ .Values.vscode.vscodePath }}
            {{- end }}
          ports:
            - name: vscode
              containerPort: {{ .Values.vscode.service.port }}
              protocol: TCP
          env:
            {{- if .Values.vscode.password }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "home-assistant.fullname" . }}-vscode
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.vscode.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          volumeMounts:
          - mountPath: /config
            name: config
          {{- if .Values.usePodSecurityContext }}
          securityContext:
            runAsUser: {{ default 0 .Values.runAsUser }}
          {{- if and (.Values.runAsUser) (.Values.fsGroup) }}
          {{- if not (eq .Values.runAsUser 0.0) }}
            fsGroup: {{ .Values.fsGroup }}
          {{- end }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.vscode.resources | indent 12 }}
        {{- end }}
      volumes:
      - name: config
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "home-assistant.fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if .Values.zwave.enabled }}
      - name: ttyacm
        hostPath:
          path: /dev/{{.Values.zwave.device}}
      {{- end }}
      {{- if .Values.zigbee.enabled }}
      - name: ttyacm1
        hostPath:
          path: /dev/{{.Values.zigbee.device}}
      {{- end }}
      {{- if .Values.hassioSupervisor.enabled }}
      - name: hassio-data
        hostPath:
          path: {{.Values.hassioSupervisor.dataDirectory }}
      {{- end}}
      {{- if .Values.hassioSupervisor.enabled }}
      - name: hassio-dsock
        hostPath:
          path: {{.Values.hassioSupervisor.dockerSock }}
      {{- end}}
      {{- if .Values.hassioSupervisor.enabled }}
      - name: hassio-dbus
        hostPath:
          path: {{.Values.hassioSupervisor.dbus }}
      {{- end}}
      {{- if .Values.git.enabled }}
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: {{ .Values.git.secret }}
      {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
