{{- if .Values.vscode.hass.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hass
  labels:
    app.kubernetes.io/name: {{ include "vscode.name" . }}
    helm.sh/chart: {{ include "vscode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.vscode.hass.hassPassword }}
  password: {{ .Values.vscode.hass.hassPassword | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.vscode.kubeHome.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kube-home
  labels:
    app.kubernetes.io/name: {{ include "vscode.name" . }}
    helm.sh/chart: {{ include "vscode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.vscode.kubeHome.kubeHomePassword }}
  password: {{ .Values.vscode.kubeHome.kubeHomePassword | b64enc | quote }}
  {{- end }}
{{- end }}
