apiVersion: v1
kind: Service
metadata:
  name: {{ template "vscode.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vscode.name" . }}
    helm.sh/chart: {{ include "vscode.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
{{- if .Values.vscode.hass.enabled }}
    - name: vs-hass
      port: {{ .Values.vscode.hass.service.port }}
      protocol: TCP
      targetPort: 80
{{ if (and (eq .Values.vscode.hass.service.type "NodePort") (not (empty .Values.vscode.hass.service.nodePort))) }}
      nodePort: {{.Values.vscode.hass.service.nodePort}}
{{ end }}
{{- end }}
{{- if .Values.vscode.kubeHome.enabled }}
    - name: vs-kube-home
      port: {{ .Values.vscode.kubeHome.service.port }}
      protocol: TCP
      targetPort: 90
{{ if (and (eq .Values.vscode.kubeHome.service.type "NodePort") (not (empty .Values.vscode.kubeHome.service.nodePort))) }}
      nodePort: {{.Values.vscode.kubeHome.service.nodePort}}
{{ end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "vscode.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
