kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana
spec:
  storageClassName: grafana
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana"
