kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vscode-kube-home
spec:
  storageClassName: vscode-kube-home
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
