kind: PersistentVolume
apiVersion: v1
metadata:
  name: vscode-hass
  labels:
    type: local
spec:
  storageClassName: vscode-hass
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/home-assistant/config"
