kind: PersistentVolume
apiVersion: v1
metadata:
  name: zm-mysql
spec:
  storageClassName: zoneminder-mysql
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zoneminder/mysql"
