kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-server
spec:
  storageClassName: prometheus-server
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus/server"
