kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pushgateway
spec:
  storageClassName: prometheus-pushgateway
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus/pushgateway"
